-- Optional manual migration for Supabase SQL Editor.
-- The application also creates these tables automatically on first start.
create table if not exists users (id varchar(36) primary key, name varchar(120) not null, email varchar(255) unique not null, phone varchar(30), password_hash varchar(255) not null, is_admin boolean not null default false, created_at timestamptz not null default now());
create table if not exists fields (id varchar(36) primary key, user_id varchar(36) not null references users(id) on delete cascade, name varchar(120) not null, district varchar(80) not null, upazila varchar(80) not null, area_bigha double precision, current_crop varchar(100), latitude double precision, longitude double precision, created_at timestamptz not null default now());
create index if not exists ix_fields_user_id on fields(user_id);
create table if not exists soil_tests (id varchar(36) primary key, field_id varchar(36) not null references fields(id) on delete cascade, ph double precision, nitrogen varchar(20), phosphorus varchar(20), potassium varchar(20), texture varchar(30), moisture double precision, drainage varchar(30), target_crop varchar(100), kit_version varchar(40) not null default 'manual-v1', verification varchar(20) not null default 'unverified', submitted_at timestamptz not null default now());
create index if not exists ix_soil_tests_field_id on soil_tests(field_id);
create table if not exists analyses (id varchar(36) primary key, test_id varchar(36) not null references soil_tests(id) on delete cascade, model_version varchar(50) not null default 'rules-v1', result jsonb not null, confidence double precision not null, requires_expert boolean not null default false, created_at timestamptz not null default now());
create table if not exists feedback (id varchar(36) primary key, analysis_id varchar(36) not null references analyses(id) on delete cascade, user_id varchar(36) not null references users(id) on delete cascade, helpful boolean not null, comment text, created_at timestamptz not null default now());
